#!/usr/bin/env node
// Generates the weekly Cashu-TS Development Meeting agenda (markdown on
// stdout), grouped by contributor like CDK's meeting agendas. Data comes
// from `gh` (must be authenticated; in CI GH_TOKEN suffices).
import { execFileSync } from 'node:child_process';

const REPO = process.env.GITHUB_REPOSITORY || 'cashubtc/cashu-ts';
const NUTS_REPO = 'cashubtc/nuts';
const DAYS_BACK = Number(process.env.DAYS_BACK || 7);
const MEETING_LINK = 'https://meet.fulmo.org/CashuTsDevs';

const since = new Date(Date.now() - DAYS_BACK * 86400_000).toISOString();
const meetingDate = new Date().toISOString().slice(0, 10);

const FIELDS = 'number,title,url,author,labels';
// Issues generated by our own automation live in their own sections
const REPORT_LABELS = ['drift', 'mutation-testing'];
const SKIP_LABELS = ['meeting-agenda'];

function gh(args) {
  const out = execFileSync('gh', args, { encoding: 'utf8', maxBuffer: 10 * 1024 * 1024 });
  return JSON.parse(out || '[]');
}

const list = (kind, repo, search, extra = []) =>
  gh([kind, 'list', '--repo', repo, '--search', search, '--json', FIELDS, ...extra]);

const merged = list('pr', REPO, `merged:>=${since}`, ['--state', 'merged', '--limit', '100']);
const newPrs = list('pr', REPO, `created:>=${since}`, ['--state', 'open', '--limit', '100']);
const activePrs = list('pr', REPO, `updated:>=${since} -created:>=${since}`, [
  '--state',
  'open',
  '--limit',
  '100',
]);
const newIssues = list('issue', REPO, `created:>=${since}`, ['--state', 'open', '--limit', '100']);
const mergedNuts = list('pr', NUTS_REPO, `merged:>=${since}`, [
  '--state',
  'merged',
  '--limit',
  '100',
]);
const newNuts = list('pr', NUTS_REPO, `created:>=${since}`, ['--state', 'open', '--limit', '100']);
const activeNuts = list('pr', NUTS_REPO, `updated:>=${since} -created:>=${since}`, [
  '--state',
  'open',
  '--limit',
  '100',
]);
const discussion = ['issue', 'pr'].flatMap((k) =>
  gh([
    k,
    'list',
    '--repo',
    REPO,
    '--state',
    'open',
    '--label',
    'meeting-discussion',
    '--json',
    FIELDS,
  ]),
);
const reports = REPORT_LABELS.flatMap((l) =>
  gh(['issue', 'list', '--repo', REPO, '--state', 'open', '--label', l, '--json', FIELDS]),
);

const hasLabel = (item, names) => (item.labels || []).some((l) => names.includes(l.name));
const skip = (item) => hasLabel(item, [...REPORT_LABELS, ...SKIP_LABELS]);
const isBackport = (pr) => /^\[backport/i.test(pr.title.trim());

// Group items by author as [type, item] pairs
const byUser = new Map();
function add(type, items, filter = () => true) {
  for (const item of items) {
    if (skip(item) || !filter(item)) continue;
    const a = item.author || {};
    const key = a.login || 'unknown';
    const display = a.name ? `${a.name} (${a.login})` : key;
    if (!byUser.has(key)) byUser.set(key, { display, rows: [] });
    byUser.get(key).rows.push(`- **${type}:** [#${item.number}](${item.url}) - ${item.title}`);
  }
}

add('Merged', merged, (pr) => !isBackport(pr));
add('New Issue', newIssues);
add('New PR', newPrs);
add('Recently Active', activePrs);
add('Backport', merged, isBackport);

const fmt = (items) =>
  items.length ? items.map((i) => `- [#${i.number}](${i.url}) - ${i.title}`).join('\n') : '- None';

// Spec activity is an ecosystem feed, not personal credit: one section,
// author inline. Open/active NUT PRs matter as much as merged ones here —
// they're what the @experimental line tracks.
const fmtNuts = (items) =>
  items.length
    ? items
        .map((i) => `- [nuts#${i.number}](${i.url}) - ${i.title} (${i.author?.login || '?'})`)
        .join('\n')
    : '- None';

const userSections = [...byUser.values()]
  .sort((a, b) => a.display.localeCompare(b.display))
  .map((u) => `### ${u.display}\n\n${u.rows.join('\n')}`)
  .join('\n\n');

console.log(`# Cashu-TS Development Meeting

${meetingDate} 11:00 UTC

Meeting Link: ${MEETING_LINK}

## Agenda By User

${userSections || '- None'}

## NUT Spec Activity

### Merged

${fmtNuts(mergedNuts)}

### New

${fmtNuts(newNuts)}

### Recently Active

${fmtNuts(activeNuts)}

## Standing Reports

${fmt(reports)}

## Discussion

${fmt([...new Map(discussion.map((d) => [d.url, d])).values()])}
`);
