coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - 'coverage/**'
  - 'docs-src/**'
  - 'examples/**'
  - 'scripts/**'
  - 'test/**'
  - 'commitlint.config.cjs'
  - '*.config.*'
