name: Nutshell integration

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and start mint
        run: |
          docker run -d -p 3338:3338 --name nutshell -e MINT_LIGHTNING_BACKEND=FakeWallet -e MINT_LISTEN_HOST=0.0.0.0 -e MINT_LISTEN_PORT=3338 -e MINT_PRIVATE_KEY=TEST_PRIVATE_KEY cashubtc/nutshell:0.15.2 poetry run mint

      - name: Check running containers
        run: docker ps

      # - name: Sleep 5 seconds and curl on localhost:3338/v1/info
      #   run: |
      #     sleep 5
      #     curl localhost:3338/v1/info

      - name: Checkout cashu-ts repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - run: npm ci
      - run: npm run compile
      - run: npm run test-integration
